- name: First Ansible Homework
  vars:
    env: "localhost"
    action: "apply"
    git_repo_dest: "~/Documents/ansible_k8s_material"
  hosts: "{{ env }}"

  tasks:
    - name: Get K8S Node Info
      command: kubectl get node
      register: k8s_info
      changed_when: true

    - name: Print Stdout
      debug:
        msg: "{{ k8s_info.stdout_lines }}"

    - name: Clone K8S homework repo and checkout branch
      ansible.builtin.git:
        repo: https://github.com/MingLunWu/kubernetes-adoption-hands-on.git
        dest: "{{ git_repo_dest  }}"
        single_branch: yes
        version: homework_22006
      when: action == "apply"

    - name: Create MySQL Related Service
      command: kubectl {{ action }} -f {{ git_repo_dest }}/homework/22006/mysql.yaml
      register: mysql_status
      changed_when: true

    - name: Create WordPress Related Service
      command: "kubectl {{ action }} -f {{ git_repo_dest }}/homework/22006/wordpress.yaml"
      register: wordpress_status
      changed_when: true

    - name: Create Nginx and Fluentd Related Service
      command: kubectl {{ action }} -f {{ git_repo_dest }}/homework/22006/nginx.yaml
      register: nginx_status
      changed_when: true

    - name: Show Deploy Status
      debug:
        msg: |
            "{{ mysql_status.stdout_lines }}"
            "{{ wordpress_status.stdout_lines }}"
            "{{ nginx_status.stdout_lines }}"

    - name: Remove git folder
      file:
        state: absent
        path: "{{ git_repo_dest }}"
      when: action == "delete"
