- name: First Ansible Homework
  vars:
    env: "localhost"
    action: "apply"
  hosts: "{{ env }}"

  tasks:
    - name: Get K8S Node Info
      command: kubectl get node
      register: k8s_info
      changed_when: true

    - name: Print Stdout
      debug:
        msg: "{{ k8s_info.stdout_lines }}"

    - name: Create MySQL Related Service
      command: kubectl {{ action }} -f group_vars/mysql/mysql.yml
      register: mysql_status
      changed_when: true

    - name: Create WordPress Related Service
      command: "kubectl {{ action }} -f group_vars/wordpress/wordpress.yml"
      register: wordpress_status
      changed_when: true

    - name: Create Nginx and Fluentd Related Service
      command: kubectl {{ action }} -f group_vars/nginx/nginx.yml
      register: nginx_status
      changed_when: true

    - name: Show Deploy Status
      debug:
        msg: |
            "{{ mysql_status.stdout_lines }}"
            "{{ wordpress_status.stdout_lines }}"
            "{{ nginx_status.stdout_lines }}"
